title: oysmlsy 的博客
email: oysmlsy@gmail.com
description: >
 some description
 by oysmlsy
author: oysmlsy
baseurl: ""
url: "oysmlsy.github.io"
permalink: /:categories/:title
excerpt_separator: '<!-- more -->'
